version: '3'

services:
  golfclub-api:
    image: golf_club_api:latest
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golf_club_db
      - spring.datasource.username=root
      - spring.datasource.password=Keyin2021
      - spring.jpa.hibernate.ddl-auto=update

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: Qap2DB
      MYSQL_ROOT_PASSWORD: Keyin2021
    ports:
      - "3306:3306"
